### ISSUE TITLE
install erro

### ISSUE THREAD

**Issue by kdpan** [yazdanimehdi/DeepDrugDomain#1]
**When I install，it seems like __version__.py is missing**

> Resolved https://gitee.com/kdpan/DeepDrugDomain.git to commit c47bedf717af5032a6d85d26bc891535a16f5f88
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [8 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-req-build-issj9v35/setup.py", line 17, in <module>
>           with open(os.path.join(package_dir[''], '__version__.py'), 'r', encoding='utf-8') as f:
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "<frozen codecs>", line 906, in open
>       FileNotFoundError: [Errno 2] No such file or directory: 'deepdrugdomain/__version__.py'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**Comment by yazdanimehdi** [comment]
Hello,
I have fixed the issue. It was file naming issue. please update your fork and try again.

**Comment by yazdanimehdi** [comment]
I'm closing this issue. Please feel free to open it if there is any more problems with installing the package.
